CREATE
USER vrgpn WITH PASSWORD 'vrgpn';
ALTER
ROLE vrgpn WITH CREATEDB;

CREATE
DATABASE vr
    WITH OWNER vrgpn
    ENCODING 'UTF-8'
    LC_COLLATE 'en_EU.UTF-8'
    LC_CTYPE 'en_EU.UTF-8'
    TEMPLATE template0;

CREATE TABLE vr_scheme.vr_zif_objects
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                       varchar(255),
    hole_project_id            INTEGER                                 NOT NULL,
    zif_uid                    varchar(255)                            NOT NULL,
    active_adaptation_value_id BIGINT                                  NOT NULL DEFAULT 0,
    creation_date              TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    active_vr_type             varchar(255),
    current_date_scheduler     TIMESTAMP WITHOUT TIME ZONE,
    scheduler_status           varchar(255),
    CONSTRAINT vr_zif_objects_pkey PRIMARY KEY (id)
);

CREATE TABLE vr_scheme.vr_adaptation_data
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vr_zif_objects_id   BIGINT                                  NOT NULL,
    name                varchar(255),
    choke_percent_adapt DOUBLE PRECISION[] NOT NULL,
    choke_value_adapt   DOUBLE PRECISION[] NOT NULL,
    date_start          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    date_end            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    creation_date       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT vr_adaptation_data_pkey PRIMARY KEY (id)
);

CREATE TABLE vr_scheme.vr_zif_additional_objects
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          varchar(255),
    zif_uid       varchar(255)                            NOT NULL,
    creation_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT vvr_zif_additional_objects_pkey PRIMARY KEY (id)
);

CREATE TABLE vr_scheme.vr_validation_data
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vr_zif_objects_id     BIGINT                                  NOT NULL,
    wct                   DOUBLE PRECISION                        NOT NULL,
    gas_condensate_factor DOUBLE PRECISION                        NOT NULL,
    is_user_value         BOOLEAN                                 NOT NULL,
    date                  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT vr_validation_data_pkey PRIMARY KEY (id)
);

CREATE TABLE vr_scheme.vr_zif_object_2_additional_object
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vr_zif_objects_id            BIGINT                                  NOT NULL,
    vr_zif_additional_objects_id BIGINT                                  NOT NULL,
    name_train                   varchar(255),
    CONSTRAINT vr_zif_object_2_additional_object_pkey PRIMARY KEY (id)
);

CREATE TABLE vr_scheme.vr_type
(
    id          varchar(255) NOT NULL,
    description varchar(255),
    CONSTRAINT vr_type_pkey PRIMARY KEY (id)
);

CREATE TABLE vr_scheme.vr_scheduler_status
(
    id          varchar(255) NOT NULL,
    description varchar(255),
    CONSTRAINT vr_scheduler_status_pkey PRIMARY KEY (id)
);

ALTER TABLE vr_scheme.vr_adaptation_data
    ADD CONSTRAINT vr_adaptation_data_fkey FOREIGN KEY (vr_zif_objects_id) REFERENCES vr_scheme.vr_zif_objects (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE vr_scheme.vr_validation_data
    ADD CONSTRAINT vr_validation_data_fkey FOREIGN KEY (vr_zif_objects_id) REFERENCES vr_scheme.vr_zif_objects (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE vr_scheme.vr_zif_object_2_additional_object
    ADD CONSTRAINT vr_zif_object_fkey FOREIGN KEY (vr_zif_objects_id) REFERENCES vr_scheme.vr_zif_objects (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE vr_scheme.vr_zif_object_2_additional_object
    ADD CONSTRAINT vr_zif_additional_object_fkey FOREIGN KEY (vr_zif_additional_objects_id) REFERENCES vr_scheme.vr_zif_additional_objects (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE vr_scheme.vr_zif_objects
    ADD CONSTRAINT active_vr_type_fkey FOREIGN KEY (active_vr_type) REFERENCES vr_scheme.vr_type (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE vr_scheme.vr_zif_objects
    ADD CONSTRAINT scheduler_status_fkey FOREIGN KEY (scheduler_status) REFERENCES vr_scheme.vr_scheduler_status (id) ON UPDATE NO ACTION ON DELETE NO ACTION;