server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    web: info
    org.springframework.r2dbc: info

springdoc:
  swagger-ui:
    enabled: true
    csrf:
      enabled: true

spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=${DB_SCHEME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

spring.security.oauth2:
  client:
    registration.service-auth:
      provider: keycloak
      authorization-grant-type: ${AUTH_SERV_GRAND_TYPE:#{client_credentials}}
      client-id: ${AUTH_SERV_CLIENT_ID}
      client-secret: ${AUTH_SERV_CLIENT_SECRET}
      scope: openid
    registration.api-auth:
      provider: keycloak
      authorization-grant-type: ${AUTH_API_GRAND_TYPE:#{authorization_code}}
      client-id: ${AUTH_API_CLIENT_ID}
      client-secret: ${AUTH_API_CLIENT_SECRET}
      scope: openid
    provider.keycloak:
      issuer-uri: ${AUTH_ISSUER_URI}
  #      user-name-attribute: realm-admin
  resourceserver.jwt.issuer-uri: ${AUTH_RESOURCE_SERVER}

cma-config:
  enable-webclient-debug-level: ${ENABLE_WEBCLIENT_DEBUG_LEVEL:false}
  #  Zif endpoints
  zif-scheme: ${ZIF_SCHEME}
  zif-host: ${ZIF_HOST}
  uri-om-object-get-all-objects-by-model: /zif-om-object/models/{id}/objects
  uri-om-object-get-include-objects-by-model: /zif-om-object/models/{id}/objects/{objId}/objects
  uri-om-object-get-object-by-id: /zif-om-object/objects/{id}
  uri-om-object-get-properties: /zif-om-object/properties
  uri-om-object-get-property: /zif-om-object/properties/{id}

  uri-om-uom-get-uom-by-id: /zif-om-uom/uoms/{id}

  uri-udl-dfa-web-api-get-values: /zif-udl-dfawebapi/restapi/RawData/{id}/values
  uri-udl-dfa-web-api-get-value: /zif-udl-dfawebapi/restapi/RawData/{id}/value
  uri-udl-dfa-web-api-get-next: /zif-udl-dfawebapi/restapi/RawData/{id}/next
  uri-udl-dfa-web-api-write-value: /zif-udl-dfawebapi/restapi/RawData/{id}/writevalue

  # VR Task endpoint
  fmm-scheme: ${FMM_SCHEME}
  fmm-host: ${FMM_HOST}
  fmm-port: ${FMM_PORT:-1}
  fmm-uri-calc-fmm-task: /v1/fmm/calc_fmm_task
  fmm-uri-calc-adapt-task: /v1/adapt/calc_adapt_task
  fmm-uri-calc-validate-task: /v1/validate/calc_validate_task

  # ML Task endpoint
  ml-scheme: ${ML_SCHEME}
  ml-host: ${ML_HOST}
  ml-port: ${ML_PORT:-1}
  ml-uri-calc-ml-task: /predict
  ml-uri-availability-of-model: /availability_of_model
  ml-uri-availability-of-service: /

  # Scheduler
  vr-type-scheduler: DATA_FOUND #FIXED_TIME, DATA_FOUND, SCHEDULER_OFF
  vr-task-scheduler-deep-validation: 30 #deep validation data
  vr-task-scheduler-check-step-after: 5
  vr-task-scheduler-cron: ${VR_TASK_CRON}
  vr-task-date-start: ${VR_TASK_DATE_START}
  vr-task-validation-count-days: ${VR_TASK_VALIDATION_COUNT_DAYS}

  # CanonicalFactor
  vr-cf-scheduler-cron: ${VR_CANONICAL_FACTOR_CRON}