include:
  - project: complex/cicd
    file:
      - build-docker.yml
      - deploy-k8s.yml

variables:
  extends: .build-variables

build:
  extends: .build-dockerfile
  variables:
    DOCKERFILE: Dockerfile
    CONTEXT: ./
    IMAGE: ''
    
push to orwin:
  extends: .build-pwd
  needs: ["build"]
  variables:
    DEST_REG: orwin.myds.me:8443/docker
#    CI_COMMIT_REF_SLUG: test
  before_script:
    - echo $REGISTRY_PASSWORD  | docker login -u $REGISTRY_USER --password-stdin $REGISTRY_INSECURE
    - echo $ORWIN_REGISTRY_PASSWORD  | docker login -u docker --password-stdin $DEST_REG
  script:
    - export CI_REGISTRY_IMAGE=$REGISTRY_INSECURE/$CI_PROJECT_PATH
    - export DEST_IMAGE=$DEST_REG/$CI_PROJECT_PATH
    - echo $DEST_IMAGE
    - echo $CI_COMMIT_REF_SLUG
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker tag  $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $DEST_IMAGE:master1
#    - docker tag  $DEST_IMAGE:$CI_COMMIT_REF_SLUG    
    - docker push $DEST_IMAGE:master1

#deploy: &deploy
#  extends: .kubectl
#  needs: ["build"]
#  variables: &vars
#    KUBECONFIG: $KUBECONFIG_DH
#    FILE: manifests/deployment.yaml
#    NAMESPACE: psd-sma-dh
  
# deploy force:
#   <<: *deploy
#   rules:
#   - when: manual

#stop:
#  <<: *deploy
#  rules:
#  - when: manual
#  script:
#  - kubectl delete -f $FILE -n $NAMESPACE || true

#start:
#  <<: *deploy
#  rules:
#  - when: manual
#  script:
#  - kubectl apply -f $FILE -n $NAMESPACE


# deploy:
#   # extends: .kubectl
#   image: debian
#   needs: ["build"]
#   variables:
#     HOST: 10.7.27.172
#     PROJECT: vr-back
#   before_script:
#   - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
#   - mkdir -p ~/.ssh
#   - cp "$SSH_PRIVATE_KEY" ~/.ssh/id_rsa
#   - chmod 400 ~/.ssh/id_rsa
#   - chmod 700 ~/.ssh
#   script:
#   - >
#     ssh -o StrictHostKeyChecking=no "docker@$HOST" -- "cd $PROJECT; docker compose up -d --pull=always --remove-orphans"
#   rules:
#     - if: '$CI_COMMIT_REF_NAME == "master"'
#     - when: never