version: '3.9'

services:
  vr-calculation-backend:
#    image: registry.gitlab.com/erg121/images/front-of-your-dream:latest #сюда можно например наш регистри в нексусе вписать
    image: nexus.okd4.inlinegroup.ru:5443/complex/dev/vr-calculation-backend:latest
    build:
      context: .
    ports:
      - 5000:5000
    network_mode: "host"
    environment:
      DB_HOST: localhost
      DB_NAME: vr
      DB_USER: vrgpn
      DB_PASSWORD: pass
      DB_PORT: 5433
      DB_SCHEME: vr_scheme
      FMM_HOST: localhost
#      FMM_PORT:
      FMM_SCHEME: https
      ML_HOST: localhost
#      ML_PORT: 8080
      ML_SCHEME: https
      ZIF_HOST: localhost
      ZIF_SCHEME: https
      VR_TASK_CRON: 0/30 * * * * *
      VR_CANONICAL_FACTOR_CRON: 0 3 * * * *
      VR_TASK_DATE_START: "2022-11-05T01:00:00.000Z"
      VR_TASK_VALIDATION_COUNT_DAYS: 30
#    volumes:
#    - ./default.conf:/etc/nginx/conf.d/default.conf
#    - ./nginx.conf:/etc/nginx/nginx.conf

# docker compose build - для билда
# docker compose push - для пуша
# docker compose up - для запуска локально
